version: "3"

services:
    prime-number:
        container_name: prime-number
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development